- name: install mariadb package (CentOS)
  tags: centos,db,mariadb
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: installe mariadb package (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu" 
